/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crossword;

public class Crossword {

  public static void main(String[] args) {
    boolean cli = args.length > 0 && args[0].equals("cli");
    if (cli) {
      new CrosswordViewCLI().run();
    } else {
      new CrosswordViewGUI().run();
    }
  }
}
